service: aws-java-service

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-west-1

package:
  artifact: build/distributions/hello.zip

functions:
  hello:
    handler: hello.Handler
    events:
      - http:
          path: hello-test
          method: get
