AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ${DefinitionUri}
      StageName: ${stage}
      Variables:
        HelloLambdaFunctionName: !Ref HelloFunction
        stage: ${stage}

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.Handler
      Runtime: java8
      CodeUri: ${CodeUri}
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /hello
            Method: ANY
            
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/'
        - '${stage}'
